### ISSUE TITLE
阿里巴巴集团员工录用通知书

### ISSUE THREAD

**Issue by Just-wy** [Ftrybe/code_generator#1]
范先生你好！
 
    经研究，公司同意录用你为Java工程师，我代表公司通知你如下事项：
 
    1、工资。考虑到公司对Java工程师职位较高的期望值及内部平衡，定为：试用期（三个月）8000元/月，试用期满9500元/月。
 
    2、福利。将公司福利制度书面通知如下：1）为员工买养老、医疗、工伤、失业、生育社会保险，包括依法应由员工个人承担的社保费用在内的全部社保费都由公司承担。社保缴费基数为1551元。2）从转正之日开始算起，每年可向公司报销1500元交通票，公司内部称为福利金。3）公司要求员工必须使用广州移动的全球通卡，以便加入公司集团网，集团网内用户在广东省地域内互打30元包月，包月费由公司划帐付给移动公司，另外，加入集团网后，个人可到营业厅申请办理集团网用户套餐，能免50元月租。4）每周双休，工作时间是8:30到12:00和13:30到17:30；五一十一黄金周按政策休7天，春节一般休10天，如有加班值班，可申请补休或补助；在公司工作满一年后，每年有5天带薪年假，如未休年假，可多领对应天数的日工资。
 
    公司要求：
 
    1、请你以职业的心态投入工作，认真提高工作技能，尽早成为一名合格的Java工程师，同时，对职业生涯要有长期的打算，并能保持踏实的工作作风。
 
    2、在转正之日起18个月之内，不得向公司提出加薪要求。
 
    如你同意上述全部安排，请回邮件给我，内中要求包括：1）我发送邮件的全部内容，2）“本人已知晓此邮件内容，并同意接受公司所作出的安排和要求”字样。具体入职手续，请见附件。
 
    入职时间：定为5月6日9点，请准备好公司要求内容，办理入职手续，特别强调，入职时，一定得提交全球通号。如对入职要求有不明之处，可打我电话咨询。
 
    致，礼！

**Comment by Ftrybe** [comment]
你好无聊啊。。。-------- 原始邮件 --------发件人： wy <notifications@github.com>日期： 2020年4月24日周五 14:03收件人： Ftrybe/code_generator <code_generator@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [Ftrybe/code_generator] 阿里巴巴集团员工录用通知书 (#1)
范先生你好！
经研究，公司同意录用你为Java工程师，我代表公司通知你如下事项：

1、工资。考虑到公司对Java工程师职位较高的期望值及内部平衡，定为：试用期（三个月）8000元/月，试用期满9500元/月。

2、福利。将公司福利制度书面通知如下：1）为员工买养老、医疗、工伤、失业、生育社会保险，包括依法应由员工个人承担的社保费用在内的全部社保费都由公司承担。社保缴费基数为1551元。2）从转正之日开始算起，每年可向公司报销1500元交通票，公司内部称为福利金。3）公司要求员工必须使用广州移动的全球通卡，以便加入公司集团网，集团网内用户在广东省地域内互打30元包月，包月费由公司划帐付给移动公司，另外，加入集团网后，个人可到营业厅申请办理集团网用户套餐，能免50元月租。4）每周双休，工作时间是8:30到12:00和13:30到17:30；五一十一黄金周按政策休7天，春节一般休10天，如有加班值班，可申请补休或补助；在公司工作满一年后，每年有5天带薪年假，如未休年假，可多领对应天数的日工资。

公司要求：

1、请你以职业的心态投入工作，认真提高工作技能，尽早成为一名合格的Java工程师，同时，对职业生涯要有长期的打算，并能保持踏实的工作作风。

2、在转正之日起18个月之内，不得向公司提出加薪要求。

如你同意上述全部安排，请回邮件给我，内中要求包括：1）我发送邮件的全部内容，2）“本人已知晓此邮件内容，并同意接受公司所作出的安排和要求”字样。具体入职手续，请见附件。

入职时间：定为5月6日9点，请准备好公司要求内容，办理入职手续，特别强调，入职时，一定得提交全球通号。如对入职要求有不明之处，可打我电话咨询。

致，礼！

**Comment by Just-wy** [comment]
试试咋用

**Comment by Just-wy** [comment]
离职！
